# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iss-tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'R.swift'
  target 'iss-trackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iss-trackerUITests' do
    # Pods for testing
  end

end
